# Generated by Django 5.1.1 on 2024-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixitup_user_id', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
                ('custom_title', models.CharField(max_length=100, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(null=True)),
                ('currency_amounts', models.JSONField(null=True)),
                ('inventory_amounts', models.JSONField(null=True)),
                ('stream_pass_amounts', models.JSONField(null=True)),
                ('is_specialty_excluded', models.BooleanField(default=False, null=True)),
                ('online_viewing_minutes', models.IntegerField(null=True)),
                ('platform_data', models.JSONField(null=True)),
                ('platform', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('avatar_link', models.URLField(null=True)),
                ('account_date', models.DateTimeField(null=True)),
                ('follow_date', models.DateTimeField(null=True)),
                ('subscribe_date', models.DateTimeField(null=True)),
                ('subscriber_tier', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
