[package]
name = "droid"  # or "droid7"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "droid_exec"  # Unique name for the executable
path = "src/main.rs"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }  # Add pyo3 dependency
